### ISSUE TITLE
Remove duplicate memory of data in _train() in dask_xgboost

### ISSUE THREAD

**Issue by xybramble** [dask/dask-xgboost#67] opened 2019-12-24 01:43 UTC
I run the project and notice in **_train()** there is a memory usage in process same as memory usage of data. However, *data* in **train_part()** (also the return value in **concat()**) also takes up the memory usage. As the **train_part()** only uses the list_of_parts, if it is possible to delete the original data after returning the list_of_parts in **_train()**?

I tried *client.cancel()* and *del* but both failed.

**Comment by TomAugspurger** [comment] 2020-01-06 21:58
Duplicate of #66 I think.

**Closed by TomAugspurger** 2020-01-06 21:58 UTC
